<?php
/**
 * @file
 * uas_default_content.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function uas_default_content_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => '1',
  'title' => 'IRC',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => 'a0568a4f-4483-3854-fdcb-f7a012890ebb',
  'type' => 'page',
  'language' => 'und',
  'created' => '1389842170',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '0375de0a-0c4e-dff4-f5cf-0166494e8122',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fringilla quam eget purus vehicula ultricies. Proin id urna bibendum, suscipit nunc et, rutrum lacus. Sed laoreet tellus eget porta viverra. Ut pretium ultricies quam, id vulputate odio rutrum vitae. Phasellus faucibus gravida orci eget venenatis. Vivamus at justo eget nisi venenatis volutpat ac quis enim. Proin porta libero imperdiet augue vestibulum congue eu convallis elit. Sed vitae leo quis felis imperdiet rhoncus at ut nisl. Sed pharetra sit amet neque ac euismod. In lorem odio, sagittis quis dui non, vulputate gravida lorem. Morbi vestibulum sollicitudin nibh, quis molestie enim convallis sed. Quisque congue porttitor commodo. Aliquam ipsum nisi, aliquam vel eros accumsan, cursus fringilla nibh. Nunc pellentesque bibendum ligula, sit amet feugiat augue bibendum in.

Nulla facilisi. Praesent venenatis velit velit, in varius dolor iaculis eget. Fusce a est a enim convallis fringilla. Cras tincidunt erat at mi imperdiet, a tristique mauris porta. Maecenas accumsan ac dolor quis cursus. Nulla facilisi. Mauris ullamcorper velit eu scelerisque auctor. Suspendisse ac ante rhoncus, malesuada mi ac, pellentesque ipsum. Phasellus lectus dui, sodales in libero quis, mollis viverra tellus. Sed porta dolor pulvinar pharetra malesuada. Pellentesque ullamcorper, nunc a varius sodales, sapien erat bibendum leo, quis malesuada purus lacus nec orci. Proin in ornare turpis. Suspendisse sodales a justo vel condimentum. Proin ac purus tincidunt, placerat justo ac, sodales arcu. In eget tincidunt augue.

Maecenas convallis, metus id tempus feugiat, augue tellus fringilla odio, nec vehicula libero diam in nisl. Duis id venenatis risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut id enim lorem. Vestibulum non mauris hendrerit, semper est eu, sagittis lectus. Fusce egestas commodo nisi, vitae commodo leo scelerisque eu. Mauris urna felis, semper non ornare eu, accumsan eget erat.

Aenean mollis euismod nunc eget bibendum. Mauris ut sollicitudin dui. Pellentesque blandit posuere elit, sit amet facilisis purus convallis ut. Mauris auctor elit sit amet ligula sodales fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse interdum, massa consectetur congue consectetur, magna risus rhoncus diam, vel auctor leo nunc porttitor tortor. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus ut est vel leo rutrum pellentesque. Proin ullamcorper adipiscing semper.

Sed nec consectetur dolor. Curabitur semper viverra ante, sit amet dapibus odio lacinia quis. In hac habitasse platea dictumst. Donec vel sapien nec dui rhoncus dapibus. Vivamus non fermentum felis. Integer sollicitudin, arcu rhoncus suscipit interdum, orci nisl pellentesque nisl, sit amet tristique metus sem eu orci. Nulla dignissim tortor velit, et convallis sem egestas eu. In ultrices, magna sed viverra rutrum, dolor nunc aliquam mi, et pharetra mi nunc sed felis. Nullam ultrices enim eu nisi rhoncus, in ultricies lectus viverra.',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fringilla quam eget purus vehicula ultricies. Proin id urna bibendum, suscipit nunc et, rutrum lacus. Sed laoreet tellus eget porta viverra. Ut pretium ultricies quam, id vulputate odio rutrum vitae. Phasellus faucibus gravida orci eget venenatis. Vivamus at justo eget nisi venenatis volutpat ac quis enim. Proin porta libero imperdiet augue vestibulum congue eu convallis elit. Sed vitae leo quis felis imperdiet rhoncus at ut nisl. Sed pharetra sit amet neque ac euismod. In lorem odio, sagittis quis dui non, vulputate gravida lorem. Morbi vestibulum sollicitudin nibh, quis molestie enim convallis sed. Quisque congue porttitor commodo. Aliquam ipsum nisi, aliquam vel eros accumsan, cursus fringilla nibh. Nunc pellentesque bibendum ligula, sit amet feugiat augue bibendum in.</p>
<p>Nulla facilisi. Praesent venenatis velit velit, in varius dolor iaculis eget. Fusce a est a enim convallis fringilla. Cras tincidunt erat at mi imperdiet, a tristique mauris porta. Maecenas accumsan ac dolor quis cursus. Nulla facilisi. Mauris ullamcorper velit eu scelerisque auctor. Suspendisse ac ante rhoncus, malesuada mi ac, pellentesque ipsum. Phasellus lectus dui, sodales in libero quis, mollis viverra tellus. Sed porta dolor pulvinar pharetra malesuada. Pellentesque ullamcorper, nunc a varius sodales, sapien erat bibendum leo, quis malesuada purus lacus nec orci. Proin in ornare turpis. Suspendisse sodales a justo vel condimentum. Proin ac purus tincidunt, placerat justo ac, sodales arcu. In eget tincidunt augue.</p>
<p>Maecenas convallis, metus id tempus feugiat, augue tellus fringilla odio, nec vehicula libero diam in nisl. Duis id venenatis risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut id enim lorem. Vestibulum non mauris hendrerit, semper est eu, sagittis lectus. Fusce egestas commodo nisi, vitae commodo leo scelerisque eu. Mauris urna felis, semper non ornare eu, accumsan eget erat.</p>
<p>Aenean mollis euismod nunc eget bibendum. Mauris ut sollicitudin dui. Pellentesque blandit posuere elit, sit amet facilisis purus convallis ut. Mauris auctor elit sit amet ligula sodales fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse interdum, massa consectetur congue consectetur, magna risus rhoncus diam, vel auctor leo nunc porttitor tortor. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus ut est vel leo rutrum pellentesque. Proin ullamcorper adipiscing semper.</p>
<p>Sed nec consectetur dolor. Curabitur semper viverra ante, sit amet dapibus odio lacinia quis. In hac habitasse platea dictumst. Donec vel sapien nec dui rhoncus dapibus. Vivamus non fermentum felis. Integer sollicitudin, arcu rhoncus suscipit interdum, orci nisl pellentesque nisl, sit amet tristique metus sem eu orci. Nulla dignissim tortor velit, et convallis sem egestas eu. In ultrices, magna sed viverra rutrum, dolor nunc aliquam mi, et pharetra mi nunc sed felis. Nullam ultrices enim eu nisi rhoncus, in ultricies lectus viverra.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => '0',
  'last_comment_name' => NULL,
  'last_comment_uid' => '1',
  'comment_count' => '0',
  'name' => 'admin',
  'picture' => '0',
  'data' => 'b:0;',
  'date' => '2014-01-15 22:16:10 -0500',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Mailing List',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => 'be706c01-488d-3f24-71dd-21d99f0768eb',
  'type' => 'page',
  'language' => 'und',
  'created' => '1389841655',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '2c5c80ea-ff11-7664-0981-106410e6e398',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fringilla quam eget purus vehicula ultricies. Proin id urna bibendum, suscipit nunc et, rutrum lacus. Sed laoreet tellus eget porta viverra. Ut pretium ultricies quam, id vulputate odio rutrum vitae. Phasellus faucibus gravida orci eget venenatis. Vivamus at justo eget nisi venenatis volutpat ac quis enim. Proin porta libero imperdiet augue vestibulum congue eu convallis elit. Sed vitae leo quis felis imperdiet rhoncus at ut nisl. Sed pharetra sit amet neque ac euismod. In lorem odio, sagittis quis dui non, vulputate gravida lorem. Morbi vestibulum sollicitudin nibh, quis molestie enim convallis sed. Quisque congue porttitor commodo. Aliquam ipsum nisi, aliquam vel eros accumsan, cursus fringilla nibh. Nunc pellentesque bibendum ligula, sit amet feugiat augue bibendum in.

Nulla facilisi. Praesent venenatis velit velit, in varius dolor iaculis eget. Fusce a est a enim convallis fringilla. Cras tincidunt erat at mi imperdiet, a tristique mauris porta. Maecenas accumsan ac dolor quis cursus. Nulla facilisi. Mauris ullamcorper velit eu scelerisque auctor. Suspendisse ac ante rhoncus, malesuada mi ac, pellentesque ipsum. Phasellus lectus dui, sodales in libero quis, mollis viverra tellus. Sed porta dolor pulvinar pharetra malesuada. Pellentesque ullamcorper, nunc a varius sodales, sapien erat bibendum leo, quis malesuada purus lacus nec orci. Proin in ornare turpis. Suspendisse sodales a justo vel condimentum. Proin ac purus tincidunt, placerat justo ac, sodales arcu. In eget tincidunt augue.

Maecenas convallis, metus id tempus feugiat, augue tellus fringilla odio, nec vehicula libero diam in nisl. Duis id venenatis risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut id enim lorem. Vestibulum non mauris hendrerit, semper est eu, sagittis lectus. Fusce egestas commodo nisi, vitae commodo leo scelerisque eu. Mauris urna felis, semper non ornare eu, accumsan eget erat.

Aenean mollis euismod nunc eget bibendum. Mauris ut sollicitudin dui. Pellentesque blandit posuere elit, sit amet facilisis purus convallis ut. Mauris auctor elit sit amet ligula sodales fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse interdum, massa consectetur congue consectetur, magna risus rhoncus diam, vel auctor leo nunc porttitor tortor. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus ut est vel leo rutrum pellentesque. Proin ullamcorper adipiscing semper.

Sed nec consectetur dolor. Curabitur semper viverra ante, sit amet dapibus odio lacinia quis. In hac habitasse platea dictumst. Donec vel sapien nec dui rhoncus dapibus. Vivamus non fermentum felis. Integer sollicitudin, arcu rhoncus suscipit interdum, orci nisl pellentesque nisl, sit amet tristique metus sem eu orci. Nulla dignissim tortor velit, et convallis sem egestas eu. In ultrices, magna sed viverra rutrum, dolor nunc aliquam mi, et pharetra mi nunc sed felis. Nullam ultrices enim eu nisi rhoncus, in ultricies lectus viverra.',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fringilla quam eget purus vehicula ultricies. Proin id urna bibendum, suscipit nunc et, rutrum lacus. Sed laoreet tellus eget porta viverra. Ut pretium ultricies quam, id vulputate odio rutrum vitae. Phasellus faucibus gravida orci eget venenatis. Vivamus at justo eget nisi venenatis volutpat ac quis enim. Proin porta libero imperdiet augue vestibulum congue eu convallis elit. Sed vitae leo quis felis imperdiet rhoncus at ut nisl. Sed pharetra sit amet neque ac euismod. In lorem odio, sagittis quis dui non, vulputate gravida lorem. Morbi vestibulum sollicitudin nibh, quis molestie enim convallis sed. Quisque congue porttitor commodo. Aliquam ipsum nisi, aliquam vel eros accumsan, cursus fringilla nibh. Nunc pellentesque bibendum ligula, sit amet feugiat augue bibendum in.</p>
<p>Nulla facilisi. Praesent venenatis velit velit, in varius dolor iaculis eget. Fusce a est a enim convallis fringilla. Cras tincidunt erat at mi imperdiet, a tristique mauris porta. Maecenas accumsan ac dolor quis cursus. Nulla facilisi. Mauris ullamcorper velit eu scelerisque auctor. Suspendisse ac ante rhoncus, malesuada mi ac, pellentesque ipsum. Phasellus lectus dui, sodales in libero quis, mollis viverra tellus. Sed porta dolor pulvinar pharetra malesuada. Pellentesque ullamcorper, nunc a varius sodales, sapien erat bibendum leo, quis malesuada purus lacus nec orci. Proin in ornare turpis. Suspendisse sodales a justo vel condimentum. Proin ac purus tincidunt, placerat justo ac, sodales arcu. In eget tincidunt augue.</p>
<p>Maecenas convallis, metus id tempus feugiat, augue tellus fringilla odio, nec vehicula libero diam in nisl. Duis id venenatis risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut id enim lorem. Vestibulum non mauris hendrerit, semper est eu, sagittis lectus. Fusce egestas commodo nisi, vitae commodo leo scelerisque eu. Mauris urna felis, semper non ornare eu, accumsan eget erat.</p>
<p>Aenean mollis euismod nunc eget bibendum. Mauris ut sollicitudin dui. Pellentesque blandit posuere elit, sit amet facilisis purus convallis ut. Mauris auctor elit sit amet ligula sodales fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse interdum, massa consectetur congue consectetur, magna risus rhoncus diam, vel auctor leo nunc porttitor tortor. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus ut est vel leo rutrum pellentesque. Proin ullamcorper adipiscing semper.</p>
<p>Sed nec consectetur dolor. Curabitur semper viverra ante, sit amet dapibus odio lacinia quis. In hac habitasse platea dictumst. Donec vel sapien nec dui rhoncus dapibus. Vivamus non fermentum felis. Integer sollicitudin, arcu rhoncus suscipit interdum, orci nisl pellentesque nisl, sit amet tristique metus sem eu orci. Nulla dignissim tortor velit, et convallis sem egestas eu. In ultrices, magna sed viverra rutrum, dolor nunc aliquam mi, et pharetra mi nunc sed felis. Nullam ultrices enim eu nisi rhoncus, in ultricies lectus viverra.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => '0',
  'last_comment_name' => NULL,
  'last_comment_uid' => '1',
  'comment_count' => '0',
  'name' => 'admin',
  'picture' => '0',
  'data' => 'b:0;',
  'date' => '2014-01-15 22:07:35 -0500',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Meetup',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '70cf2070-64b4-4a74-65c6-68a9db4ac36b',
  'type' => 'page',
  'language' => 'und',
  'created' => '1389841712',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '8cae71ee-0606-2834-7d5c-a37cc681bd44',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fringilla quam eget purus vehicula ultricies. Proin id urna bibendum, suscipit nunc et, rutrum lacus. Sed laoreet tellus eget porta viverra. Ut pretium ultricies quam, id vulputate odio rutrum vitae. Phasellus faucibus gravida orci eget venenatis. Vivamus at justo eget nisi venenatis volutpat ac quis enim. Proin porta libero imperdiet augue vestibulum congue eu convallis elit. Sed vitae leo quis felis imperdiet rhoncus at ut nisl. Sed pharetra sit amet neque ac euismod. In lorem odio, sagittis quis dui non, vulputate gravida lorem. Morbi vestibulum sollicitudin nibh, quis molestie enim convallis sed. Quisque congue porttitor commodo. Aliquam ipsum nisi, aliquam vel eros accumsan, cursus fringilla nibh. Nunc pellentesque bibendum ligula, sit amet feugiat augue bibendum in.

Nulla facilisi. Praesent venenatis velit velit, in varius dolor iaculis eget. Fusce a est a enim convallis fringilla. Cras tincidunt erat at mi imperdiet, a tristique mauris porta. Maecenas accumsan ac dolor quis cursus. Nulla facilisi. Mauris ullamcorper velit eu scelerisque auctor. Suspendisse ac ante rhoncus, malesuada mi ac, pellentesque ipsum. Phasellus lectus dui, sodales in libero quis, mollis viverra tellus. Sed porta dolor pulvinar pharetra malesuada. Pellentesque ullamcorper, nunc a varius sodales, sapien erat bibendum leo, quis malesuada purus lacus nec orci. Proin in ornare turpis. Suspendisse sodales a justo vel condimentum. Proin ac purus tincidunt, placerat justo ac, sodales arcu. In eget tincidunt augue.

Maecenas convallis, metus id tempus feugiat, augue tellus fringilla odio, nec vehicula libero diam in nisl. Duis id venenatis risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut id enim lorem. Vestibulum non mauris hendrerit, semper est eu, sagittis lectus. Fusce egestas commodo nisi, vitae commodo leo scelerisque eu. Mauris urna felis, semper non ornare eu, accumsan eget erat.

Aenean mollis euismod nunc eget bibendum. Mauris ut sollicitudin dui. Pellentesque blandit posuere elit, sit amet facilisis purus convallis ut. Mauris auctor elit sit amet ligula sodales fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse interdum, massa consectetur congue consectetur, magna risus rhoncus diam, vel auctor leo nunc porttitor tortor. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus ut est vel leo rutrum pellentesque. Proin ullamcorper adipiscing semper.

Sed nec consectetur dolor. Curabitur semper viverra ante, sit amet dapibus odio lacinia quis. In hac habitasse platea dictumst. Donec vel sapien nec dui rhoncus dapibus. Vivamus non fermentum felis. Integer sollicitudin, arcu rhoncus suscipit interdum, orci nisl pellentesque nisl, sit amet tristique metus sem eu orci. Nulla dignissim tortor velit, et convallis sem egestas eu. In ultrices, magna sed viverra rutrum, dolor nunc aliquam mi, et pharetra mi nunc sed felis. Nullam ultrices enim eu nisi rhoncus, in ultricies lectus viverra.',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fringilla quam eget purus vehicula ultricies. Proin id urna bibendum, suscipit nunc et, rutrum lacus. Sed laoreet tellus eget porta viverra. Ut pretium ultricies quam, id vulputate odio rutrum vitae. Phasellus faucibus gravida orci eget venenatis. Vivamus at justo eget nisi venenatis volutpat ac quis enim. Proin porta libero imperdiet augue vestibulum congue eu convallis elit. Sed vitae leo quis felis imperdiet rhoncus at ut nisl. Sed pharetra sit amet neque ac euismod. In lorem odio, sagittis quis dui non, vulputate gravida lorem. Morbi vestibulum sollicitudin nibh, quis molestie enim convallis sed. Quisque congue porttitor commodo. Aliquam ipsum nisi, aliquam vel eros accumsan, cursus fringilla nibh. Nunc pellentesque bibendum ligula, sit amet feugiat augue bibendum in.</p>
<p>Nulla facilisi. Praesent venenatis velit velit, in varius dolor iaculis eget. Fusce a est a enim convallis fringilla. Cras tincidunt erat at mi imperdiet, a tristique mauris porta. Maecenas accumsan ac dolor quis cursus. Nulla facilisi. Mauris ullamcorper velit eu scelerisque auctor. Suspendisse ac ante rhoncus, malesuada mi ac, pellentesque ipsum. Phasellus lectus dui, sodales in libero quis, mollis viverra tellus. Sed porta dolor pulvinar pharetra malesuada. Pellentesque ullamcorper, nunc a varius sodales, sapien erat bibendum leo, quis malesuada purus lacus nec orci. Proin in ornare turpis. Suspendisse sodales a justo vel condimentum. Proin ac purus tincidunt, placerat justo ac, sodales arcu. In eget tincidunt augue.</p>
<p>Maecenas convallis, metus id tempus feugiat, augue tellus fringilla odio, nec vehicula libero diam in nisl. Duis id venenatis risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut id enim lorem. Vestibulum non mauris hendrerit, semper est eu, sagittis lectus. Fusce egestas commodo nisi, vitae commodo leo scelerisque eu. Mauris urna felis, semper non ornare eu, accumsan eget erat.</p>
<p>Aenean mollis euismod nunc eget bibendum. Mauris ut sollicitudin dui. Pellentesque blandit posuere elit, sit amet facilisis purus convallis ut. Mauris auctor elit sit amet ligula sodales fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse interdum, massa consectetur congue consectetur, magna risus rhoncus diam, vel auctor leo nunc porttitor tortor. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus ut est vel leo rutrum pellentesque. Proin ullamcorper adipiscing semper.</p>
<p>Sed nec consectetur dolor. Curabitur semper viverra ante, sit amet dapibus odio lacinia quis. In hac habitasse platea dictumst. Donec vel sapien nec dui rhoncus dapibus. Vivamus non fermentum felis. Integer sollicitudin, arcu rhoncus suscipit interdum, orci nisl pellentesque nisl, sit amet tristique metus sem eu orci. Nulla dignissim tortor velit, et convallis sem egestas eu. In ultrices, magna sed viverra rutrum, dolor nunc aliquam mi, et pharetra mi nunc sed felis. Nullam ultrices enim eu nisi rhoncus, in ultricies lectus viverra.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => '0',
  'last_comment_name' => NULL,
  'last_comment_uid' => '1',
  'comment_count' => '0',
  'name' => 'admin',
  'picture' => '0',
  'data' => 'b:0;',
  'date' => '2014-01-15 22:08:32 -0500',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Get Involved',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => 'a2068597-f22e-c354-e1a9-3c00231f53c7',
  'type' => 'page',
  'language' => 'und',
  'created' => '1389837785',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => 'd0566db1-a909-41e4-110b-9f883785ae98',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id sem sed felis semper consequat at nec nunc. Mauris cursus ipsum arcu, nec dapibus sapien ultrices et. Aenean in massa varius, placerat nibh eu, convallis mauris. Integer volutpat nisl quis arcu consectetur posuere. Aliquam consequat magna nec fringilla lacinia. Etiam a metus non nisi pretium laoreet. Integer aliquam consequat elit. In feugiat suscipit mi vel varius. Aliquam erat volutpat. Etiam tempus nulla et enim bibendum, eget consequat sapien aliquet. Mauris malesuada porta nibh, eget adipiscing lacus vestibulum in. Etiam semper tincidunt pretium. Nam quis lacus sollicitudin, lobortis dui scelerisque, venenatis ligula. Quisque a massa id lacus consectetur semper eget in urna. Phasellus hendrerit leo enim, quis interdum diam volutpat eget. Integer tristique hendrerit luctus.

Morbi et lectus consectetur, viverra lectus id, convallis eros. Fusce magna mauris, lacinia mattis pellentesque eget, vulputate at elit. Aliquam pharetra malesuada varius. Etiam nunc erat, scelerisque ut sapien sed, tempor volutpat tortor. Fusce ligula magna, feugiat ac ultrices vel, lobortis ac augue. Nullam at felis non magna convallis vehicula. Ut lacinia nulla id pretium mollis. Curabitur fringilla tempus augue ac congue.

Nullam ut tortor nisi. Curabitur congue ultricies nisi eu pellentesque. Proin tincidunt rutrum odio quis molestie. Curabitur ut auctor turpis, in ullamcorper nibh. Donec rutrum tellus sit amet diam adipiscing, vitae consectetur ligula sollicitudin. Nullam pulvinar velit ac justo mollis, quis malesuada sem fringilla. Mauris pharetra elementum ligula non laoreet. Maecenas quis ultricies ante. Duis pharetra, massa nec fermentum aliquam, massa velit commodo nisl, in cursus massa lorem et nunc. Phasellus interdum risus eu erat egestas, ut sollicitudin velit elementum. Curabitur vel sapien mauris. Phasellus condimentum libero non velit commodo, ac fermentum sem fringilla. Aenean imperdiet varius lorem vel vulputate. Vestibulum viverra nisi non tortor suscipit, vitae aliquet magna adipiscing. Sed vulputate ante at tellus fermentum, sit amet fermentum urna porta.

Etiam ut nunc a enim posuere mollis. Praesent placerat risus magna, lacinia venenatis velit luctus quis. Duis hendrerit cursus placerat. Sed eu interdum orci, nec ornare turpis. Aliquam erat volutpat. Suspendisse potenti. Aenean scelerisque et erat hendrerit consequat. Suspendisse sodales libero turpis. Ut id gravida quam, sit amet vulputate eros. Fusce et quam eu mauris porta porttitor. Cras ut dui condimentum, posuere nulla sit amet, sollicitudin magna. Aenean tincidunt laoreet metus sit amet faucibus.

Mauris nec libero et purus tristique dignissim nec eu ipsum. Pellentesque faucibus eget justo sodales blandit. Curabitur vel tincidunt urna. Nulla tristique dolor sed felis venenatis fringilla. Phasellus malesuada posuere justo id aliquam. Nulla vel nisl vitae mi pulvinar faucibus. Cras vel neque sed justo imperdiet bibendum sed nec nisi. Mauris sed lectus sem. Proin rutrum imperdiet ullamcorper. Nam quis leo risus. Nam nec tellus sed nisl pellentesque mattis sit amet at metus.',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id sem sed felis semper consequat at nec nunc. Mauris cursus ipsum arcu, nec dapibus sapien ultrices et. Aenean in massa varius, placerat nibh eu, convallis mauris. Integer volutpat nisl quis arcu consectetur posuere. Aliquam consequat magna nec fringilla lacinia. Etiam a metus non nisi pretium laoreet. Integer aliquam consequat elit. In feugiat suscipit mi vel varius. Aliquam erat volutpat. Etiam tempus nulla et enim bibendum, eget consequat sapien aliquet. Mauris malesuada porta nibh, eget adipiscing lacus vestibulum in. Etiam semper tincidunt pretium. Nam quis lacus sollicitudin, lobortis dui scelerisque, venenatis ligula. Quisque a massa id lacus consectetur semper eget in urna. Phasellus hendrerit leo enim, quis interdum diam volutpat eget. Integer tristique hendrerit luctus.</p>
<p>Morbi et lectus consectetur, viverra lectus id, convallis eros. Fusce magna mauris, lacinia mattis pellentesque eget, vulputate at elit. Aliquam pharetra malesuada varius. Etiam nunc erat, scelerisque ut sapien sed, tempor volutpat tortor. Fusce ligula magna, feugiat ac ultrices vel, lobortis ac augue. Nullam at felis non magna convallis vehicula. Ut lacinia nulla id pretium mollis. Curabitur fringilla tempus augue ac congue.</p>
<p>Nullam ut tortor nisi. Curabitur congue ultricies nisi eu pellentesque. Proin tincidunt rutrum odio quis molestie. Curabitur ut auctor turpis, in ullamcorper nibh. Donec rutrum tellus sit amet diam adipiscing, vitae consectetur ligula sollicitudin. Nullam pulvinar velit ac justo mollis, quis malesuada sem fringilla. Mauris pharetra elementum ligula non laoreet. Maecenas quis ultricies ante. Duis pharetra, massa nec fermentum aliquam, massa velit commodo nisl, in cursus massa lorem et nunc. Phasellus interdum risus eu erat egestas, ut sollicitudin velit elementum. Curabitur vel sapien mauris. Phasellus condimentum libero non velit commodo, ac fermentum sem fringilla. Aenean imperdiet varius lorem vel vulputate. Vestibulum viverra nisi non tortor suscipit, vitae aliquet magna adipiscing. Sed vulputate ante at tellus fermentum, sit amet fermentum urna porta.</p>
<p>Etiam ut nunc a enim posuere mollis. Praesent placerat risus magna, lacinia venenatis velit luctus quis. Duis hendrerit cursus placerat. Sed eu interdum orci, nec ornare turpis. Aliquam erat volutpat. Suspendisse potenti. Aenean scelerisque et erat hendrerit consequat. Suspendisse sodales libero turpis. Ut id gravida quam, sit amet vulputate eros. Fusce et quam eu mauris porta porttitor. Cras ut dui condimentum, posuere nulla sit amet, sollicitudin magna. Aenean tincidunt laoreet metus sit amet faucibus.</p>
<p>Mauris nec libero et purus tristique dignissim nec eu ipsum. Pellentesque faucibus eget justo sodales blandit. Curabitur vel tincidunt urna. Nulla tristique dolor sed felis venenatis fringilla. Phasellus malesuada posuere justo id aliquam. Nulla vel nisl vitae mi pulvinar faucibus. Cras vel neque sed justo imperdiet bibendum sed nec nisi. Mauris sed lectus sem. Proin rutrum imperdiet ullamcorper. Nam quis leo risus. Nam nec tellus sed nisl pellentesque mattis sit amet at metus.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => '0',
  'last_comment_name' => NULL,
  'last_comment_uid' => '1',
  'comment_count' => '0',
  'name' => 'admin',
  'picture' => '0',
  'data' => 'b:0;',
  'date' => '2014-01-15 21:03:05 -0500',
);
  return $nodes;
}
