<?php
/**
 * @file
 * uas_default_content.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function uas_default_content_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => '1',
  'title' => 'Get Involved',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => 'a2068597-f22e-c354-e1a9-3c00231f53c7',
  'type' => 'page',
  'language' => 'und',
  'created' => '1389837785',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => 'd0566db1-a909-41e4-110b-9f883785ae98',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id sem sed felis semper consequat at nec nunc. Mauris cursus ipsum arcu, nec dapibus sapien ultrices et. Aenean in massa varius, placerat nibh eu, convallis mauris. Integer volutpat nisl quis arcu consectetur posuere. Aliquam consequat magna nec fringilla lacinia. Etiam a metus non nisi pretium laoreet. Integer aliquam consequat elit. In feugiat suscipit mi vel varius. Aliquam erat volutpat. Etiam tempus nulla et enim bibendum, eget consequat sapien aliquet. Mauris malesuada porta nibh, eget adipiscing lacus vestibulum in. Etiam semper tincidunt pretium. Nam quis lacus sollicitudin, lobortis dui scelerisque, venenatis ligula. Quisque a massa id lacus consectetur semper eget in urna. Phasellus hendrerit leo enim, quis interdum diam volutpat eget. Integer tristique hendrerit luctus.

Morbi et lectus consectetur, viverra lectus id, convallis eros. Fusce magna mauris, lacinia mattis pellentesque eget, vulputate at elit. Aliquam pharetra malesuada varius. Etiam nunc erat, scelerisque ut sapien sed, tempor volutpat tortor. Fusce ligula magna, feugiat ac ultrices vel, lobortis ac augue. Nullam at felis non magna convallis vehicula. Ut lacinia nulla id pretium mollis. Curabitur fringilla tempus augue ac congue.

Nullam ut tortor nisi. Curabitur congue ultricies nisi eu pellentesque. Proin tincidunt rutrum odio quis molestie. Curabitur ut auctor turpis, in ullamcorper nibh. Donec rutrum tellus sit amet diam adipiscing, vitae consectetur ligula sollicitudin. Nullam pulvinar velit ac justo mollis, quis malesuada sem fringilla. Mauris pharetra elementum ligula non laoreet. Maecenas quis ultricies ante. Duis pharetra, massa nec fermentum aliquam, massa velit commodo nisl, in cursus massa lorem et nunc. Phasellus interdum risus eu erat egestas, ut sollicitudin velit elementum. Curabitur vel sapien mauris. Phasellus condimentum libero non velit commodo, ac fermentum sem fringilla. Aenean imperdiet varius lorem vel vulputate. Vestibulum viverra nisi non tortor suscipit, vitae aliquet magna adipiscing. Sed vulputate ante at tellus fermentum, sit amet fermentum urna porta.

Etiam ut nunc a enim posuere mollis. Praesent placerat risus magna, lacinia venenatis velit luctus quis. Duis hendrerit cursus placerat. Sed eu interdum orci, nec ornare turpis. Aliquam erat volutpat. Suspendisse potenti. Aenean scelerisque et erat hendrerit consequat. Suspendisse sodales libero turpis. Ut id gravida quam, sit amet vulputate eros. Fusce et quam eu mauris porta porttitor. Cras ut dui condimentum, posuere nulla sit amet, sollicitudin magna. Aenean tincidunt laoreet metus sit amet faucibus.

Mauris nec libero et purus tristique dignissim nec eu ipsum. Pellentesque faucibus eget justo sodales blandit. Curabitur vel tincidunt urna. Nulla tristique dolor sed felis venenatis fringilla. Phasellus malesuada posuere justo id aliquam. Nulla vel nisl vitae mi pulvinar faucibus. Cras vel neque sed justo imperdiet bibendum sed nec nisi. Mauris sed lectus sem. Proin rutrum imperdiet ullamcorper. Nam quis leo risus. Nam nec tellus sed nisl pellentesque mattis sit amet at metus.',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id sem sed felis semper consequat at nec nunc. Mauris cursus ipsum arcu, nec dapibus sapien ultrices et. Aenean in massa varius, placerat nibh eu, convallis mauris. Integer volutpat nisl quis arcu consectetur posuere. Aliquam consequat magna nec fringilla lacinia. Etiam a metus non nisi pretium laoreet. Integer aliquam consequat elit. In feugiat suscipit mi vel varius. Aliquam erat volutpat. Etiam tempus nulla et enim bibendum, eget consequat sapien aliquet. Mauris malesuada porta nibh, eget adipiscing lacus vestibulum in. Etiam semper tincidunt pretium. Nam quis lacus sollicitudin, lobortis dui scelerisque, venenatis ligula. Quisque a massa id lacus consectetur semper eget in urna. Phasellus hendrerit leo enim, quis interdum diam volutpat eget. Integer tristique hendrerit luctus.</p>
<p>Morbi et lectus consectetur, viverra lectus id, convallis eros. Fusce magna mauris, lacinia mattis pellentesque eget, vulputate at elit. Aliquam pharetra malesuada varius. Etiam nunc erat, scelerisque ut sapien sed, tempor volutpat tortor. Fusce ligula magna, feugiat ac ultrices vel, lobortis ac augue. Nullam at felis non magna convallis vehicula. Ut lacinia nulla id pretium mollis. Curabitur fringilla tempus augue ac congue.</p>
<p>Nullam ut tortor nisi. Curabitur congue ultricies nisi eu pellentesque. Proin tincidunt rutrum odio quis molestie. Curabitur ut auctor turpis, in ullamcorper nibh. Donec rutrum tellus sit amet diam adipiscing, vitae consectetur ligula sollicitudin. Nullam pulvinar velit ac justo mollis, quis malesuada sem fringilla. Mauris pharetra elementum ligula non laoreet. Maecenas quis ultricies ante. Duis pharetra, massa nec fermentum aliquam, massa velit commodo nisl, in cursus massa lorem et nunc. Phasellus interdum risus eu erat egestas, ut sollicitudin velit elementum. Curabitur vel sapien mauris. Phasellus condimentum libero non velit commodo, ac fermentum sem fringilla. Aenean imperdiet varius lorem vel vulputate. Vestibulum viverra nisi non tortor suscipit, vitae aliquet magna adipiscing. Sed vulputate ante at tellus fermentum, sit amet fermentum urna porta.</p>
<p>Etiam ut nunc a enim posuere mollis. Praesent placerat risus magna, lacinia venenatis velit luctus quis. Duis hendrerit cursus placerat. Sed eu interdum orci, nec ornare turpis. Aliquam erat volutpat. Suspendisse potenti. Aenean scelerisque et erat hendrerit consequat. Suspendisse sodales libero turpis. Ut id gravida quam, sit amet vulputate eros. Fusce et quam eu mauris porta porttitor. Cras ut dui condimentum, posuere nulla sit amet, sollicitudin magna. Aenean tincidunt laoreet metus sit amet faucibus.</p>
<p>Mauris nec libero et purus tristique dignissim nec eu ipsum. Pellentesque faucibus eget justo sodales blandit. Curabitur vel tincidunt urna. Nulla tristique dolor sed felis venenatis fringilla. Phasellus malesuada posuere justo id aliquam. Nulla vel nisl vitae mi pulvinar faucibus. Cras vel neque sed justo imperdiet bibendum sed nec nisi. Mauris sed lectus sem. Proin rutrum imperdiet ullamcorper. Nam quis leo risus. Nam nec tellus sed nisl pellentesque mattis sit amet at metus.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => '0',
  'last_comment_name' => NULL,
  'last_comment_uid' => '1',
  'comment_count' => '0',
  'name' => 'admin',
  'picture' => '0',
  'data' => 'b:0;',
  'date' => '2014-01-15 21:03:05 -0500',
);
  return $nodes;
}
